export const topBarHeight = 64;
export const sideNavWidth = 205;
export const navbarHeight = 60;
export const sidenavCompactWidth = 80;
export const containedLayoutWidth = 1200;
// export const SERVER_API_URL = 'http://192.168.0.42:8082';
export const SERVER_API_URL = 'http://localhost:8081/api';
export const SUCCESS_CREATE_MESSAGE = 'Successfully Created';
export const SUCCESS_UPDATE_MESSAGE = 'Successfully Updated';
export const SUCCESS_DELETE_MESSAGE = 'Successfully Deleted';
export const ERROR_CREATE_MESSAGE = 'Error occured on Create';
export const ERROR_UPDATE_MESSAGE = 'Error occured on Update';
export const ERROR_DELETE_MESSAGE = 'Error occured on Delete';
export const ROWS_PER_PAGE = 10;
export const APP_DATETIME_FORMAT = 'YYYY-MM-DD HH:mm:ss';

export const AUTHORITIES = {
  ADMIN: 'ADMIN',
  SETTINGS: 'SETTINGS',
  DASHBOARD: 'DASHBOARD',
  USER_CREATE: 'USER:CREATE',
  USER_UPDATE: 'USER:UPDATE',
  USER_DELETE: 'USER:DELETE',
  USER_READ: 'USER:READ',
  ROLE_CREATE: 'ROLE:CREATE',
  ROLE_UPDATE: 'ROLE:UPDATE',
  ROLE_DELETE: 'ROLE:DELETE',
  ROLE_READ: 'ROLE:READ',
  REPORT_SIGTAS: 'REPORT:SIGTAS',
  REPORT_4250_TRANSIT: 'REPORT:4250-TRANSIT',
  REPORT_4550_DPS: 'REPORT:4550-DPS',
  REPORT_4551_DPS: 'REPORT:4551-DPS',
  REPORT_4556_DPS: 'REPORT:4556-DPS',
  REPORT_4554_DPS: 'REPORT:4554-DPS',
  REPORT_4555_DPS: 'REPORT:4555-DPS',
  REPORT_4558_DPS: 'REPORT:4558-DPS',
  REPORT_4561_DPS: 'REPORT:4561-DPS',
  REPORT_4564_DPS: 'REPORT:4564-DPS',
  REPORT_4571_DPS: 'REPORT:4571-DPS',
  REPORT_4565_DPS: 'REPORT:4565-DPS',
  REPORT_4566_DPS: 'REPORT:4566-DPS',
  REPORT_4562_DPS: 'REPORT:4562-DPS',
  REPORT_4560_DPS: 'REPORT:4560-DPS',
  REPORT_4559_DPS: 'REPORT:4559-DPS',
  REPORT_4563_DPS: 'REPORT:4563-DPS',
  REPORT_4150_REVENUE: 'REPORT:4150-REVENUE'
};
